### ISSUE TITLE
请教App Trace看板无数据的问题

### ISSUE THREAD

**Issue by zxmfke** [songjiayang/prometheus-exemplar#7]
请教一下，app trace为什么没有数据呀，但是在explore里面通过trace id又可以找到数据
![image](https://github.com/grafanafans/prometheus-exemplar/assets/19350643/a463335f-efad-4b71-9292-9c84be913e60)

**Comment by songjiayang** [comment]
这里需要一个特定 trace id 才能看到 App trace 的某个具体trace 的tree 图表。
